### ISSUE TITLE
Team Orientation (LT)

### ISSUE THREAD

**Issue by lortrent** [Capital-Regional-District/projects#18]
#Description:
Coaching and orientation of the team to project processes, tools, working documents, schedule and roles and responsibilities and next steps.

#Outcome:
- [x]  Access to IT HRIS Sharepoint folders and files.
- [x] Review of project charter and working documents
- [x] Review sprint process and agree on sprint planning, stand ups - how often, backlog grooming, reviews and retros.
