### ISSUE TITLE
Learning Requirements Analysis

### ISSUE THREAD

**Issue by lortrent** [Capital-Regional-District/projects#21]
#Description:

All activities to understand learning at a detailed enough level to configure the learning module and address the goals of the project.

#Outcomes:
- [ ] Current Business Process model(s) 
- [ ]  Supporting Narrative(s)
- [ ] Future Process Map(s)
- [ ] Future Supporting Narrative(s)
- [ ] Completed Tasks from the SAP Configuration Playbook
- [ ] New Risks and Issues
- [ ] Instructions for Measuring Critical Success Factors
